category:
  url:      /category/:slug
  class:    sfPropelRoute
  param:    { module: category, action: show }
  options:  { model: JobeetCategory, type: object }

job:
  class:   sfPropelRouteCollection
  options:
    model:          JobeetJob
    column:         token
    object_actions: { publish: put }
  requirements:
    token: \w+

job_show_user:
  url:     /job/:token
  class:   sfPropelRoute
  options:
    model: JobeetJob
    type:  object
    method_for_criteria: doSelectActive
    column: token
  param:   { module: job, action: show }
  requirements:
    token: \w+
    sf_method: [get]

homepage:
  url:   /
  param: { module: job, action: index }
